import './globals.css'

import type { Metadata } from 'next'

import NextAuthProvider from '@/providers/next-auth-provider'

import ReactQueryProvider from '../providers/react-query-provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <ReactQueryProvider>
          <body className={` antialiased`}>{children}</body>
        </ReactQueryProvider>
      </NextAuthProvider>
    </html>
  )
}
